title: Victor Ehikioya
logo: /assets/img/me.jpeg
description: Cloud Engineer 
[ðŸ‘º](https://twitter.com/VictorRaeva/)

show_downloads: false
theme: jekyll-theme-minimal
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
